index:
   path: /
   controller: App\Controller\AccueilController::index



admin_accueil:
  path: /admin
  controller: App\Controller\AdminController::index

inscrit_accueil:
  path: /inscrit
  controller: App\Controller\InscritController::index
